export function createInitialState() {
	return {
		sources: [],
		assets: [],
		selectedItemId: null,
		selectedItemIds: [],
		viewerItemId: null,
		selectedProviderId: "example",
		activeSourceFilter: "all",
		selectedCollectionId: "all",
		selectedCollectionIds: [],
		currentLevel: "collections",
		metadataMode: "collection",
		mobileView: "browse",
		openedCollectionId: null,
		publishDestination: null,
		manifest: null,
		opfsAvailable: false,
		opfsStatus: "Checking local draft storage...",
		lastLocalSaveAt: "",
		hasLocalDraft: false,
		hasUnsavedChanges: false,
		lastSaveTarget: "",
		publishInProgress: false,
		publishError: "",
		lastPublishResult: null,
		isDropTargetActive: false,
		localDraftCollections: [],
		browserViewModes: {
			collections: "cards",
			items: "cards",
		},
		inspectorPlacement: "right",
		connectionsDialogView: "list",
	};
}
