export function createInitialState() {
  return {
    sources: [],
    assets: [],
    selectedItemId: null,
    viewerItemId: null,
    selectedProviderId: 'example',
    activeSourceFilter: 'all',
    selectedCollectionId: 'all',
    currentLevel: 'collections',
    metadataMode: 'collection',
    mobileEditorOpen: false,
    openedCollectionId: null,
    publishDestination: null,
    manifest: null,
    opfsAvailable: false,
    opfsStatus: 'Checking local draft storage...',
    lastLocalSaveAt: '',
    hasLocalDraft: false,
    hasUnsavedChanges: false,
    lastSaveTarget: '',
    publishInProgress: false,
    publishError: '',
    isDropTargetActive: false,
    localDraftCollections: [],
    browserViewModes: {
      collections: 'cards',
      items: 'cards',
    },
    inspectorPlacement: 'right',
  };
}
