<?php

if (! defined('ABSPATH')) {
    exit;
}

class Open_Collections_Protocol
{
    /**
     * @var Open_Collections_Settings
     */
    private $settings;

    /**
     * @param Open_Collections_Settings $settings
     */
    public function __construct($settings)
    {
        $this->settings = $settings;
    }

    /**
     * Register lightweight protocol-facing REST stubs to clarify output direction.
     */
    public function register_rest_routes()
    {
        register_rest_route(
            'open-collections/v1',
            '/collection.json',
            array(
                'methods'             => WP_REST_Server::READABLE,
                'callback'            => array($this, 'render_collection_stub'),
                'permission_callback' => '__return_true',
            )
        );

        register_rest_route(
            'open-collections/v1',
            '/items/(?P<item_id>[a-zA-Z0-9_-]+)',
            array(
                'methods'             => WP_REST_Server::READABLE,
                'callback'            => array($this, 'render_item_stub'),
                'permission_callback' => '__return_true',
            )
        );

        register_rest_route(
            'open-collections/v1',
            '/media/(?P<path>.+)',
            array(
                'methods'             => WP_REST_Server::READABLE,
                'callback'            => array($this, 'render_media_stub'),
                'permission_callback' => '__return_true',
            )
        );
    }

    /**
     * Handle optional domain-owned collections discovery output at /.well-known/collections.json.
     */
    public function maybe_render_dcd_output()
    {
        $request_uri = isset($_SERVER['REQUEST_URI']) ? wp_unslash($_SERVER['REQUEST_URI']) : '';
        $request_path = wp_parse_url($request_uri, PHP_URL_PATH);

        if ($request_path !== '/.well-known/collections.json') {
            return;
        }

        $options = $this->settings->get_options();

        if (empty($options['enable_dcd'])) {
            return;
        }

        wp_send_json(
            array(
                'openCollections' => array(
                    'version'     => OPEN_COLLECTIONS_VERSION,
                    'description' => 'DCD output placeholder. Wire to real published collections in a later pass.',
                    'collections' => array(
                        array(
                            'id'           => 'wordpress-primary',
                            'manifest_url' => rest_url('open-collections/v1/collection.json'),
                        ),
                    ),
                ),
            )
        );
    }

    public function render_collection_stub()
    {
        $config = $this->settings->build_manager_config();

        return rest_ensure_response(
            array(
                'id'      => 'wordpress-primary',
                'title'   => get_bloginfo('name') . ' Collection (MVP Stub)',
                'summary' => 'Open Collections Protocol collection.json placeholder generated by the WordPress integration plugin.',
                'links'   => array(
                    'self'  => rest_url('open-collections/v1/collection.json'),
                    'items' => rest_url('open-collections/v1/items/{itemId}'),
                    'media' => rest_url('open-collections/v1/media/{path}'),
                ),
                'config'  => array(
                    'collectionRoot' => $config['output']['collectionRoot'],
                    'outputBaseUrl'  => $config['output']['outputBaseUrl'],
                    'provider'       => $config['provider'],
                ),
            )
        );
    }

    public function render_item_stub($request)
    {
        return rest_ensure_response(
            array(
                'id'      => sanitize_text_field($request['item_id']),
                'title'   => 'Item detail placeholder',
                'message' => 'This route is a stub that reserves a stable URL shape for protocol item detail outputs.',
            )
        );
    }

    public function render_media_stub($request)
    {
        return rest_ensure_response(
            array(
                'path'    => sanitize_text_field($request['path']),
                'message' => 'Media output placeholder. Future passes should map this route to provider/media storage.',
            )
        );
    }
}
